//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
namespace Util.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Util.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 {
        ///  &quot;DesIvCBC&quot;: [ 105, 201, 30, 91, 252, 202, 43, 69 ],
        ///  &quot;DesKeyCBC&quot;: [ 74, 4, 36, 14, 193, 4, 156, 80 ],
        ///  //&quot;DesIvCFB&quot;: [ 114, 88, 1, 59, 168, 248, 168, 2 ],
        ///  //&quot;DesKeyCFB&quot;: [ 67, 207, 247, 41, 19, 113, 32, 134 ],
        ///  &quot;DesIvECB&quot;: [ 70, 178, 8, 47, 192, 104, 102, 42 ],
        ///  &quot;DesKeyECB&quot;: [ 75, 221, 226, 170, 207, 164, 37, 26 ],
        ///  //&quot;DesIvOFB&quot;: [ 3, 200, 103, 122, 151, 197, 254, 53 ],
        ///  //&quot;DesKeyOFB&quot;: [ 238, 90, 222, 172, 224, 27, 40, 88 ],
        ///  &quot;Des3Key&quot;: [ 36, 194, 80, 213, 250, 203, 209, 253, 126, 46,  [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string SecurityConfig {
            get {
                return ResourceManager.GetString("SecurityConfig", resourceCulture);
            }
        }
    }
}
