//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DescriptionModel.Simulate.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DescriptionModel.Simulate.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 {
        ///    &quot;name&quot;: {
        ///        &quot;first&quot;: [ &quot;王&quot;, &quot;李&quot;, &quot;张&quot;, &quot;刘&quot;, &quot;郑&quot;, &quot;梁&quot;, &quot;谢&quot;, &quot;唐&quot;, &quot;丁&quot;, &quot;蒋&quot;, &quot;程&quot;, &quot;余&quot;, &quot;贾&quot;, &quot;范&quot;, &quot;金&quot;, &quot;方&quot;, &quot;季&quot;, &quot;史&quot;, &quot;陶&quot;, &quot;毛&quot;, &quot;严&quot;, &quot;文&quot;, &quot;常&quot;, &quot;牛&quot;, &quot;陈&quot;, &quot;杨&quot;, &quot;黄&quot;, &quot;赵&quot;, &quot;许&quot;, &quot;冯&quot;, &quot;宋&quot;, &quot;韩&quot;, &quot;吕&quot;, &quot;魏&quot;, &quot;蔡&quot;, &quot;苏&quot;, &quot;韦&quot;, &quot;夏&quot;, &quot;廖&quot;, &quot;侯&quot;, &quot;贺&quot;, &quot;龙&quot;, &quot;万&quot;, &quot;顾&quot;, &quot;莫&quot;, &quot;洪&quot;, &quot;米&quot;, &quot;康&quot;, &quot;周&quot;, &quot;吴&quot;, &quot;徐&quot;, &quot;孙&quot;, &quot;邓&quot;, &quot;彭&quot;, &quot;曹&quot;, &quot;曾&quot;, &quot;任&quot;, &quot;卢&quot;, &quot;沈&quot;, &quot;姜&quot;, &quot;白&quot;, &quot;孟&quot;, &quot;邹&quot;, &quot;秦&quot;, &quo... 的本地化字符串。
        /// </summary>
        internal static string basedata {
            get {
                return ResourceManager.GetString("basedata", resourceCulture);
            }
        }
    }
}
